service: senate-stacks
plugins:
  - serverless-offline
  - '@jimdo/serverless-dotenv'

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-west-2

functions:
  legislators:
    handler: handler.legislators
      - http:
          path: state/{state}
          method: get